name: spark-substrait-gateway-env
channels:
  - conda-forge
dependencies:
  - pip
  - pre-commit
  - grpcio >= 1.48.1
  - grpcio-status
  - grpcio-tools
  - pytest >= 7.0.0
  - python >= 3.10.0
  - setuptools >= 61.0.0
  - setuptools_scm >= 6.2.0
  - python-substrait
  - Faker
  - pip:
    - adbc_driver_manager
    - pyarrow
    - duckdb
    - datafusion
    - pyspark
    - pandas >= 1.0.5
    - substrait-validator
