name: spark-substrait-gateway-env
channels:
  - conda-forge
dependencies:
  - arrow-cpp
  - astroid
  - aws-c-auth
  - aws-c-cal
  - aws-c-common
  - aws-c-compression
  - aws-c-event-stream
  - aws-c-http
  - aws-c-io
  - aws-c-mqtt
  - aws-c-s3
  - aws-c-sdkutils
  - aws-checksums
  - aws-crt-cpp
  - aws-sdk-cpp
  - bzip2
  - c-ares
  - ca-certificates
  - cffi
  - cfgv
  - colorama
  - dill
  - distlib
  - exceptiongroup
  - faker
  - filelock
  - gflags
  - glog
  - googleapis-common-protos
  - grpcio
  - grpcio-status
  - grpcio-tools
  - identify
  - iniconfig
  - isort
  - krb5
  - libabseil
  - libarrow
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcblas
  - libcrc32c
  - libcurl
  - libcxx
  - libedit
  - libev
  - libevent
  - libexpat
  - libffi
  - libgfortran
  - libgfortran5
  - libgoogle-cloud
  - libgoogle-cloud-storage
  - libgrpc
  - liblapack
  - libnghttp2
  - libopenblas
  - libprotobuf
  - libre2-11
  - libsqlite
  - libssh2
  - libthrift
  - libutf8proc
  - libzlib
  - llvm-openmp
  - lz4-c
  - mccabe
  - mypy-protobuf
  - ncurses
  - nodeenv
  - numpy
  - openssl
  - orc
  - packaging
  - pip
  - platformdirs
  - pluggy
  - pre-commit
  - protobuf
  - pycparser
  - pylint
  - pytest
  - python
  - python-dateutil
  - python-substrait
  - python_abi
  - pyyaml
  - re2
  - readline
  - setuptools
  - setuptools-scm
  - setuptools_scm
  - six
  - snappy
  - tk
  - tomli
  - tomlkit
  - types-futures
  - types-protobuf
  - typing-extensions
  - typing_extensions
  - ukkonen
  - virtualenv
  - wheel
  - xz
  - yaml
  - zlib
  - zstd
  - pip:
    - adbc-driver-manager
    - buf
    - cargo
    - click
    - datafusion
    - docopt
    - duckdb
    - jdot
    - mypy
    - mypy-extensions
    - pandas
    - proto-matcher
    - py4j
    - pyarrow
    - pyhamcrest
    - pyspark
    - pytest-pycharm
    - pytest-timeout
    - pytz
    - ruff
    - substrait
    - substrait-validator
    - tabulate
    - tzdata
