name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base
        python -m pip install -r requirements.txt -v
    - name: Analyzing the code using ruff
      uses: chartboost/ruff-action@v1
        with:
          target-version = "py312"
