name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        $CONDA/bin/conda env update --file environment.yml --name base
        python -m pip install --upgrade pip
        python -m pip install adbc_driver_manager substrait-validator
        $CONDA/bin/conda install pylint">=3.1.0"
    - name: Analysing the code with pylint
      run: |
        $CONDA/bin/pylint $(git ls-files '*.py')
